### ISSUE TITLE
will not join channel

### ISSUE THREAD

**Issue by rinzes** [blha303/Twitter-IRC-Bridge#4]
The bot will join the server but not the #channel

I have the following in the config:

twusers: {dutch: "#options"}

**Comment by blha303** [comment]
The account twitter.com/dutch has been suspended, the program wasn't made to handle that situation

**Comment by blha303** [comment]
Ah, and the program is using an outdated Twitter API, that's more likely to be the cause. I'll see if I can fix it.

**Comment by blha303** [comment]
Can't figure out why it doesn't work, the request should succeed but it doesn't, and I haven't used this script in a loooong time. I can't fix this, sorry.
